# open repository settings -> Secrets and variables -> Actions
# Add 3 secrets: SERVER_HOST, SERVER_PORT, SERVER_USER, SERVER_SSH

# rsync

# actions/checkout@v3
# actions/setup-java@v3
# gradle/gradle-build-action@v2 -> https://github.com/gradle/gradle-build-action
# actions/upload-artifact@v3 -> https://github.com/actions/upload-artifact
# actions/download-artifact@v3 -> https://github.com/actions/download-artifact
# easingthemes/ssh-deploy@main -> https://github.com/easingthemes/ssh-deploy

name: Deploy to Remote server (as service)

on:
  push:
    branches:
      - main

env:
  INSTALL_SERVICE: true

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build
          cache-disabled: true

      - name: Rename JAR
        run: mv build/libs/ivl-github-actions-0.0.1-SNAPSHOT.jar ivl-github-actions.jar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: |
            ivl-github-actions.jar
            scripts/
          if-no-files-found: error
          retention-days: 1

  deploy:
    needs: build
    name: Deploy to Remote server
    runs-on: ubuntu-22.04

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact

      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        env:
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_PORT: ${{ secrets.SERVER_PORT }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH }}
          TARGET: /appcfg/github-actions

  post_deploy:
    needs: deploy
    name: Post deploy actions on remote server
    runs-on: ubuntu-22.04

    steps:
      - name: Install service
        if: env.INSTALL_SERVICE == 'true'
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH }}
          script: |
            mkdir /appcfg/jar
            cp /appcfg/github-actions/ivl-github-actions.jar /appcfg/jar/ivl-github-actions.jar
            sudo mv /appcfg/github-actions/ivl-github-actions.service /etc/systemd/system/ivl-github-actions.service

      - name: Restart service
        if: env.INSTALL_SERVICE != 'true'
        run: echo "123 Restart service"

      - name: Remove github-actions folder
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH }}
          script: rm -dfr /appcfg/github-actions

